# Generated by Django 5.2.6 on 2025-09-24 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Electronics', 'Clothing')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of category name', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'inventory_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in currency units', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.IntegerField(default=0, help_text='Available stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit - unique product identifier', max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='items/')),
                ('is_active', models.BooleanField(default=True, help_text='Is product available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When product was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When product was last modified')),
                ('restocked_at', models.DateTimeField(auto_now=True, help_text='When product was last restocked')),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.category')),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Positive for additions (restock), negative for reductions (sale)')),
                ('reason', models.CharField(help_text="Why stock changed: 'restock', 'sale', 'adjustment'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.item')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='inventory_i_categor_b03a42_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['price'], name='inventory_i_price_b49247_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='inventory_i_created_875751_idx'),
        ),
    ]
