# Generated by Django 5.2.6 on 2025-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number for order delivery.", max_length=15, null=True),
        ),
    ]
